from django.db import models
from django.conf import settings


class MonitoringSession(models.Model):
    """A monitoring session for a student."""

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='monitoring_sessions',
    )
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-start_time']

    def __str__(self):
        return f"Session: {self.student.username} ({self.start_time.strftime('%Y-%m-%d %H:%M')})"

    @property
    def duration_minutes(self):
        if self.end_time:
            return (self.end_time - self.start_time).total_seconds() / 60
        return 0


class Screenshot(models.Model):
    """Automatic screenshot captured by the monitoring agent."""

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='screenshots',
    )
    session = models.ForeignKey(
        MonitoringSession,
        on_delete=models.CASCADE,
        related_name='screenshots',
        blank=True,
        null=True,
    )
    image = models.ImageField(upload_to='screenshots/%Y/%m/%d/')
    captured_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-captured_at']

    def __str__(self):
        return f"Screenshot: {self.student.username} at {self.captured_at.strftime('%Y-%m-%d %H:%M')}"


class AppUsage(models.Model):
    """Track which applications the student is using."""

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='app_usages',
    )
    session = models.ForeignKey(
        MonitoringSession,
        on_delete=models.CASCADE,
        related_name='app_usages',
        blank=True,
        null=True,
    )
    app_name = models.CharField(max_length=255)
    window_title = models.CharField(max_length=500, blank=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True)
    duration_seconds = models.PositiveIntegerField(default=0)
    is_idle = models.BooleanField(default=False)

    class Meta:
        ordering = ['-start_time']

    def __str__(self):
        return f"{self.student.username}: {self.app_name} ({self.duration_seconds}s)"


class KeyboardActivity(models.Model):
    """Track keyboard activity patterns."""

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='keyboard_activities',
    )
    session = models.ForeignKey(
        MonitoringSession,
        on_delete=models.CASCADE,
        related_name='keyboard_activities',
        blank=True,
        null=True,
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    typing_duration_seconds = models.PositiveIntegerField(default=0)
    total_keystrokes = models.PositiveIntegerField(default=0)
    deletion_count = models.PositiveIntegerField(default=0)
    edit_count = models.PositiveIntegerField(default=0)
    interval_minutes = models.PositiveIntegerField(default=5, help_text='Reporting interval in minutes')

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.student.username}: {self.total_keystrokes} keys at {self.timestamp.strftime('%H:%M')}"


class ActivityAlert(models.Model):
    """Alerts generated by the monitoring system."""

    class AlertType(models.TextChoices):
        INACTIVITY = 'inactivity', 'Inactivity'
        HIGH_DELETION = 'high_deletion', 'High Deletion Rate'
        UNKNOWN_APP = 'unknown_app', 'Unknown Application'
        UNUSUAL = 'unusual', 'Unusual Behavior'

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='activity_alerts',
    )
    alert_type = models.CharField(
        max_length=20,
        choices=AlertType.choices,
    )
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_reviewed = models.BooleanField(default=False)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='reviewed_alerts',
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Alert: {self.student.username} - {self.get_alert_type_display()}"


class Attendance(models.Model):
    """Daily attendance record for a student."""

    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='attendance_records',
    )
    date = models.DateField(auto_now_add=True)
    is_present = models.BooleanField(default=True)
    total_active_seconds = models.PositiveIntegerField(default=0)
    last_seen = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['student', 'date']
        ordering = ['-date']

    def __str__(self):
        return f"{self.student.username} - {self.date} ({'Present' if self.is_present else 'Absent'})"
