# Generated by Django 5.2.8 on 2026-05-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringAgentApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('file', models.FileField(upload_to='agent_builds/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Desktop Agent Package',
                'verbose_name_plural': 'Desktop Agent Packages',
            },
        ),
    ]
